version: '2'

services:
  nginx:
    build: ./images/nginx
    ports:
        - "80:80"
        - "443:443"
    links:
      - php:php
    volumes:
      - ./nginx-dynamic-vhost.conf:/etc/nginx/conf.d/default.conf
      - ${CODE}:/srv/www
  php:
    build: ./images/php-fpm 
    volumes:
      - ${CODE}:/srv/www
      - ./xdebug.ini:/usr/local/etc/php/conf.d/20-xdebug.ini
    links:
      - mariadb:mariadb
      - mailhog:mailhog
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
    expose:
      - 9000
  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
        - mariadb:/var/lib/mysql
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
  dnsmasq:
    build: 
      context: "./images/dnsmasq"
    ports: 
      - 53:53/udp
    dns:
      - ${DNS}

volumes:
  mariadb:
